export const mockWorkflowDetails = {
  workflow: {
    variables: {
      variable: [
        {
          defaultValue: null,
          displayName: "Deployment Name",
          name: "params.deployment_name",
          startIncrement: 0,
          type: "String",
          mandatoryArray: false,
          visible: true,
          description: "",
          groupSeparator: "",
          groupDisplayName: "",
          maxLength: 100,
          displayOrder: 0,
          increment: 0,
          refServiceURI: "",
          refDeviceIdVar: null,
          keepOnImport: false,
          editable: false,
          onlyDetailView: false,
          localVarNameMatch: "",
          remoteVarNameMatch: "",
          arrayCanAdd: true,
          arrayCanRemove: true,
          arrayCanMove: true,
          arrayCanEdit: true,
          mandatory: false,
          userLocked: false,
          grouped: false,
          searchable: false,
          uniqueGlobal: false,
          selector: null,
          defaultValueLong: null,
          displayNameHeader: "",
          fullDisplayName: "",
          isCompositeKey: false,
          codeLanguage: null,
          behaviour: null,
          indexVariables: null,
          sections: null,
          sdTypes: null,
          class: null,
          values: null,
          repositories: null,
        },
        {
          defaultValue: null,
          displayName: "Deployment Description",
          name: "params.deployment_desc",
          startIncrement: 0,
          type: "String",
          mandatoryArray: false,
          visible: true,
          description: "",
          groupSeparator: "",
          groupDisplayName: "",
          maxLength: 100,
          displayOrder: 0,
          increment: 0,
          refServiceURI: "",
          refDeviceIdVar: null,
          keepOnImport: false,
          editable: false,
          onlyDetailView: false,
          localVarNameMatch: "",
          remoteVarNameMatch: "",
          arrayCanAdd: true,
          arrayCanRemove: true,
          arrayCanMove: true,
          arrayCanEdit: true,
          mandatory: false,
          userLocked: false,
          grouped: false,
          searchable: false,
          uniqueGlobal: false,
          selector: null,
          defaultValueLong: null,
          displayNameHeader: "",
          fullDisplayName: "",
          isCompositeKey: false,
          codeLanguage: null,
          behaviour: null,
          indexVariables: null,
          sections: null,
          sdTypes: null,
          class: null,
          values: null,
          repositories: null,
        },
        {
          defaultValue: null,
          displayName: "EKS Cluster Managed Entity (ME)",
          name: "params.env_infrastructure_me",
          startIncrement: 0,
          type: "Device",
          mandatoryArray: false,
          visible: false,
          description: "",
          groupSeparator: "",
          groupDisplayName: "",
          maxLength: 100,
          displayOrder: 0,
          increment: 0,
          refServiceURI: "",
          refDeviceIdVar: null,
          keepOnImport: false,
          editable: false,
          onlyDetailView: false,
          localVarNameMatch: "",
          remoteVarNameMatch: "",
          arrayCanAdd: true,
          arrayCanRemove: true,
          arrayCanMove: true,
          arrayCanEdit: true,
          mandatory: true,
          userLocked: false,
          grouped: false,
          searchable: false,
          uniqueGlobal: false,
          selector: null,
          defaultValueLong: null,
          displayNameHeader: "",
          fullDisplayName: "",
          isCompositeKey: false,
          codeLanguage: null,
          behaviour: null,
          indexVariables: null,
          sections: null,
          sdTypes: null,
          class: null,
          values: null,
          repositories: null,
        },
        {
          defaultValue: null,
          displayName: "App Name",
          name: "params.apps_to_deploy.0.app_name",
          startIncrement: 0,
          type: "String",
          mandatoryArray: false,
          visible: true,
          description: "",
          groupSeparator: "",
          groupDisplayName: "",
          maxLength: 150,
          displayOrder: 0,
          increment: 0,
          refServiceURI: "",
          refDeviceIdVar: null,
          keepOnImport: false,
          editable: false,
          onlyDetailView: false,
          localVarNameMatch: "",
          remoteVarNameMatch: "",
          arrayCanAdd: false,
          arrayCanRemove: true,
          arrayCanMove: true,
          arrayCanEdit: true,
          mandatory: false,
          userLocked: false,
          grouped: false,
          searchable: false,
          uniqueGlobal: false,
          selector: null,
          defaultValueLong: null,
          displayNameHeader: "",
          fullDisplayName: "",
          isCompositeKey: false,
          codeLanguage: null,
          behaviour: null,
          indexVariables: null,
          sections: null,
          sdTypes: null,
          class: null,
          values: null,
          repositories: null,
        },
        {
          defaultValue: null,
          displayName: "App Image",
          name: "params.apps_to_deploy.0.app_image",
          startIncrement: 0,
          type: "String",
          mandatoryArray: false,
          visible: true,
          description: "",
          groupSeparator: "",
          groupDisplayName: "",
          maxLength: 120,
          displayOrder: 0,
          increment: 0,
          refServiceURI: "",
          refDeviceIdVar: null,
          keepOnImport: false,
          editable: false,
          onlyDetailView: false,
          localVarNameMatch: "",
          remoteVarNameMatch: "",
          arrayCanAdd: false,
          arrayCanRemove: true,
          arrayCanMove: true,
          arrayCanEdit: true,
          mandatory: false,
          userLocked: true,
          grouped: false,
          searchable: false,
          uniqueGlobal: false,
          selector: null,
          defaultValueLong: null,
          displayNameHeader: "",
          fullDisplayName: "",
          isCompositeKey: false,
          codeLanguage: null,
          behaviour: null,
          indexVariables: null,
          sections: null,
          sdTypes: null,
          class: null,
          values: null,
          repositories: null,
        },
        {
          defaultValue: null,
          displayName: "App Description",
          name: "params.apps_to_deploy.0.short_description",
          startIncrement: 0,
          type: "String",
          mandatoryArray: false,
          visible: true,
          description: "",
          groupSeparator: "",
          groupDisplayName: "",
          maxLength: 400,
          displayOrder: 10,
          increment: 0,
          refServiceURI: "",
          refDeviceIdVar: null,
          keepOnImport: false,
          editable: false,
          onlyDetailView: false,
          localVarNameMatch: "",
          remoteVarNameMatch: "",
          arrayCanAdd: false,
          arrayCanRemove: true,
          arrayCanMove: true,
          arrayCanEdit: true,
          mandatory: false,
          userLocked: false,
          grouped: false,
          searchable: false,
          uniqueGlobal: false,
          selector: null,
          defaultValueLong: null,
          displayNameHeader: "",
          fullDisplayName: "",
          isCompositeKey: false,
          codeLanguage: null,
          behaviour: null,
          indexVariables: null,
          sections: null,
          sdTypes: null,
          class: null,
          values: null,
          repositories: null,
        },
        {
          defaultValue: null,
          displayName: "App Version",
          name: "params.apps_to_deploy.0.version",
          startIncrement: 0,
          type: "String",
          mandatoryArray: false,
          visible: false,
          description: "",
          groupSeparator: "",
          groupDisplayName: "",
          maxLength: 100,
          displayOrder: 8,
          increment: 0,
          refServiceURI: "",
          refDeviceIdVar: null,
          keepOnImport: false,
          editable: false,
          onlyDetailView: false,
          localVarNameMatch: "",
          remoteVarNameMatch: "",
          arrayCanAdd: false,
          arrayCanRemove: true,
          arrayCanMove: true,
          arrayCanEdit: true,
          mandatory: false,
          userLocked: false,
          grouped: false,
          searchable: false,
          uniqueGlobal: false,
          selector: null,
          defaultValueLong: null,
          displayNameHeader: "",
          fullDisplayName: "",
          isCompositeKey: false,
          codeLanguage: null,
          behaviour: null,
          indexVariables: null,
          sections: null,
          sdTypes: null,
          class: null,
          values: null,
          repositories: null,
        },
        {
          defaultValue: "1",
          displayName: "App Replicas",
          name: "params.apps_to_deploy.0.app_replicas",
          startIncrement: 0,
          type: "Integer",
          mandatoryArray: false,
          visible: true,
          description: "",
          groupSeparator: "",
          groupDisplayName: "",
          maxLength: 70,
          displayOrder: 0,
          increment: 0,
          refServiceURI: "",
          refDeviceIdVar: null,
          keepOnImport: false,
          editable: false,
          onlyDetailView: false,
          localVarNameMatch: "",
          remoteVarNameMatch: "",
          arrayCanAdd: false,
          arrayCanRemove: true,
          arrayCanMove: true,
          arrayCanEdit: true,
          mandatory: false,
          userLocked: false,
          grouped: false,
          searchable: false,
          uniqueGlobal: false,
          selector: null,
          defaultValueLong: null,
          displayNameHeader: "",
          fullDisplayName: "",
          isCompositeKey: false,
          codeLanguage: null,
          behaviour: null,
          indexVariables: null,
          sections: null,
          sdTypes: null,
          class: null,
          values: null,
          repositories: null,
        },
        {
          defaultValue: null,
          displayName: "App Port",
          name: "params.apps_to_deploy.0.app_port",
          startIncrement: 0,
          type: "Integer",
          mandatoryArray: false,
          visible: true,
          description: "",
          groupSeparator: "",
          groupDisplayName: "",
          maxLength: 100,
          displayOrder: 0,
          increment: 0,
          refServiceURI: "",
          refDeviceIdVar: null,
          keepOnImport: false,
          editable: false,
          onlyDetailView: false,
          localVarNameMatch: "",
          remoteVarNameMatch: "",
          arrayCanAdd: false,
          arrayCanRemove: true,
          arrayCanMove: true,
          arrayCanEdit: true,
          mandatory: false,
          userLocked: false,
          grouped: false,
          searchable: false,
          uniqueGlobal: false,
          selector: null,
          defaultValueLong: null,
          displayNameHeader: "",
          fullDisplayName: "",
          isCompositeKey: false,
          codeLanguage: null,
          behaviour: null,
          indexVariables: null,
          sections: null,
          sdTypes: null,
          class: null,
          values: null,
          repositories: null,
        },
        {
          defaultValue: null,
          displayName: "App Node Port",
          name: "params.apps_to_deploy.0.app_node_port",
          startIncrement: 0,
          type: "Integer",
          mandatoryArray: false,
          visible: true,
          description: "",
          groupSeparator: "",
          groupDisplayName: "",
          maxLength: 100,
          displayOrder: 0,
          increment: 0,
          refServiceURI: "",
          refDeviceIdVar: null,
          keepOnImport: false,
          editable: false,
          onlyDetailView: false,
          localVarNameMatch: "",
          remoteVarNameMatch: "",
          arrayCanAdd: false,
          arrayCanRemove: true,
          arrayCanMove: true,
          arrayCanEdit: true,
          mandatory: false,
          userLocked: false,
          grouped: false,
          searchable: false,
          uniqueGlobal: false,
          selector: null,
          defaultValueLong: null,
          displayNameHeader: "",
          fullDisplayName: "",
          isCompositeKey: false,
          codeLanguage: null,
          behaviour: null,
          indexVariables: null,
          sections: null,
          sdTypes: null,
          class: null,
          values: null,
          repositories: null,
        },
        {
          defaultValue: null,
          displayName: "App Logo",
          name: "params.apps_to_deploy.0.logo_url",
          startIncrement: 0,
          type: "String",
          mandatoryArray: false,
          visible: true,
          description: "",
          groupSeparator: "",
          groupDisplayName: "",
          maxLength: 200,
          displayOrder: 9,
          increment: 0,
          refServiceURI: "",
          refDeviceIdVar: null,
          keepOnImport: false,
          editable: false,
          onlyDetailView: false,
          localVarNameMatch: "",
          remoteVarNameMatch: "",
          arrayCanAdd: false,
          arrayCanRemove: true,
          arrayCanMove: true,
          arrayCanEdit: true,
          mandatory: false,
          userLocked: true,
          grouped: false,
          searchable: false,
          uniqueGlobal: false,
          selector: null,
          defaultValueLong: null,
          displayNameHeader: "",
          fullDisplayName: "",
          isCompositeKey: false,
          codeLanguage: null,
          behaviour: null,
          indexVariables: null,
          sections: null,
          sdTypes: null,
          class: null,
          values: null,
          repositories: null,
        },
      ],
      frozen: 0,
    },
    example: null,
    process: [
      {
        name:
          "Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Process_create_instance",
        displayName: "create instance",
        type: "CREATE",
        visibility: 5,
        allowSchedule: null,
        tasks: [
          {
            displayName: "update var",
            fileName: "Task_update_var.py",
            fileUri:
              "/opt/fmc_repository/Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Process_create_instance/Tasks",
          },
          {
            displayName: "task 2",
            fileName: "Task_task_2.py",
            fileUri:
              "/opt/fmc_repository/Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Process_create_instance/Tasks",
          },
        ],
      },
      {
        name:
          "Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Process_Generate_Application_WF",
        displayName: "  New APP deployment",
        type: "CREATE",
        visibility: 5,
        allowSchedule: null,
        tasks: [
          {
            displayName: "Create TF Workspace",
            fileName: "Task_Create_TF_Workspace.py",
            fileUri:
              "/opt/fmc_repository/Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Process_Generate_Application_WF/Tasks",
          },
          {
            displayName: "Set variables values",
            fileName: "Task_Set_variables_values.py",
            fileUri:
              "/opt/fmc_repository/Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Process_Generate_Application_WF/Tasks",
          },
          {
            displayName: "Initialize TF Workspace",
            fileName: "Task_Initialize_TF_Workspace.py",
            fileUri:
              "/opt/fmc_repository/Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Process_Generate_Application_WF/Tasks",
          },
          {
            displayName: "Provisioning Application",
            fileName: "Task_Provisioning_Application.py",
            fileUri:
              "/opt/fmc_repository/Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Process_Generate_Application_WF/Tasks",
          },
        ],
      },
      {
        name:
          "Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Process_Generate_Application_WF",
        displayName: "Restart APP",
        type: "UPDATE",
        visibility: 5,
        allowSchedule: null,
        tasks: null,
      },
      {
        name:
          "Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Process_Resume_APP",
        displayName: "Resume APP",
        type: "UPDATE",
        visibility: 5,
        allowSchedule: null,
        tasks: null,
      },
      {
        name:
          "Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Process_Pause_APP",
        displayName: "Pause APP",
        type: "UPDATE",
        visibility: 5,
        allowSchedule: null,
        tasks: null,
      },
      {
        name:
          "Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Process_Backup_APP",
        displayName: "Backup APP",
        type: "UPDATE",
        visibility: 5,
        allowSchedule: null,
        tasks: null,
      },
      {
        name:
          "Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Process_Restore_APP",
        displayName: "Restore APP",
        type: "UPDATE",
        visibility: 5,
        allowSchedule: null,
        tasks: null,
      },
      {
        name:
          "Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Process_Upgrade_APP",
        displayName: "Upgrade APP",
        type: "UPDATE",
        visibility: 5,
        allowSchedule: null,
        tasks: null,
      },
      {
        name:
          "Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Process_Scale_APP",
        displayName: "Scale APP",
        type: "UPDATE",
        visibility: 5,
        allowSchedule: null,
        tasks: null,
      },
      {
        name:
          "Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Process_Tear_Down_APP",
        displayName: "Tear Down APP",
        type: "UPDATE",
        visibility: 5,
        allowSchedule: null,
        tasks: [
          {
            displayName: "Terminate Application instance",
            fileName: "Task_Terminate_Application_instance.py",
            fileUri:
              "/opt/fmc_repository/Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Process_Tear_Down_APP/Tasks",
          },
        ],
      },
      {
        name:
          "Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Process_Delete_Service",
        displayName: "Delete Service",
        type: "DELETE",
        visibility: 5,
        allowSchedule: null,
        tasks: [
          {
            displayName: "Delete service",
            fileName: "Task_Delete_service.py",
            fileUri:
              "/opt/fmc_repository/Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Process_Delete_Service/Tasks",
          },
        ],
      },
    ],
    information: {
      displayName: "[APP] Provision EKS Apps(AWS)",
      icon: null,
      description:
        "This workflow allows to provision application in AWS Elastic Kubernetes Service (EKS) cluster based-on terraform configuration.",
      category: "Cloud|APP",
      displayField: "service_id",
      serviceTaskType: "python",
      order: 10000,
      visibility: 5,
    },
    metaInformationList: [
      {
        type: "FILE",
        name: "Provision_Apps_EKS_Cluster.xml",
        displayName: "Provision_Apps_EKS_Cluster.xml",
        repositoryName: "Process",
        parentURI: "Process/cloudclapp-wf/Provision_Apps_EKS_Cluster",
        fileType: "text",
        tag: null,
        comment: null,
        modelId: 0,
        vendorId: 0,
        file: true,
        uri:
          "Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Provision_Apps_EKS_Cluster.xml",
        serviceName:
          "Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Provision_Apps_EKS_Cluster",
      },
    ],
  },
  workflowInstance: {
    apps_to_deploy: [
      {
        app_name: "nginx",
        logo_url:
          "https://d1q6f0aelx0por.cloudfront.net/product-logos/library-nginx-logo.png",
        app_replicas: "1",
        slug: "nginx",
        short_description: "Official build of Nginx.",
        app_port: "80",
        app_node_port: "8080",
      },
      {
        short_description:
          "Node.js is a JavaScript-based platform for server-side and networking applications.",
        logo_url:
          "https://d1q6f0aelx0por.cloudfront.net/product-logos/library-node-logo.png",
        app_name: "node",
        slug: "node",
      },
    ],
    TASKINSTANCEID: "11792",
    deployment_name: "Nginx and Node",
    env_infrastructure_me: "00p323",
    EXECNUMBER: "1",
    UBIQUBEID: "00pA144",
    SERVICEINSTANCEREFERENCE: "00pSID126104",
    TASKID: "1",
    PROCESSINSTANCEID: "132430",
    deployment_desc: "2apps",
    service_id: "126104",
    SERVICEINSTANCEID: "126104",
  },
  workflowStatus: {
    serviceId: {
      name:
        "Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Provision_Apps_EKS_Cluster",
      id: 126104,
      serviceExternalReference: "00pSID126104",
      state: null,
    },
    processId: {
      name:
        "Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Process_create_instance",
      id: 132430,
      lastExecNumber: 1,
      submissionType: "RUN",
    },
    status: {
      status: "ENDED",
      details: "Task OK",
      startingDate: "2022-03-13T19:18:34.334Z",
      endingDate: "2022-03-13T19:18:35.424Z",
      execNumber: 1,
      processReference: "00pPID132430",
      processTaskStatus: [
        {
          status: "ENDED",
          order: 1,
          processInstanceId: 132430,
          scriptName: "update var",
          details: "Task OK",
          startingDate: "2022-03-14 00:48:34.845658",
          endingDate: "2022-03-14 00:48:35.424707",
          newParameters: [],
        },
      ],
    },
    executorUsername: "hto@openmsa.com",
  },
  isLoading: false,
  loading: {
    isWorkflowLoading: false,
    isWorkflowInstanceLoading: false,
    isWorkflowStatusLoading: false,
  },
};

export const environment = {
  envName: "hto env 01",
  envId: 144,
  envUbiqubeId: "00pA144",
  description: "2nd",
  cloudVendor: "Cloud/AWS",
  orgName: "htoExtRef",
  envIp: "127.0.0.1",
  envHostname: "",
  username: "1",
  envReference: "0419674e-a030-4fb9-b47a-94bcb8de6d0e",
  importFlag: false,
  serviceId: null,
  serviceName: null,
  envWFUri:
    "Process/cloudclapp-wf/Provision_an_EKS_Cluster__AWS_/Provision_an_EKS_Cluster__AWS_",
  appWFUri:
    "Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Provision_Apps_EKS_Cluster",
  deploymentCount: 5,
  userCount: 1,
  scanData: null,
  cclapOwner: 125,
  envEntityId: 323,
  status: "OK",
};

export const environmentsList = [
  {
    envName: "hto env 00",
    envId: 143,
    envReference: "a5f1f04d-2d38-47d5-bf12-5a10bf094568",
    status: "NEVERREACHED",
    cclapOwner: 125,
    deployments: [
      {
        deploymentId: "126090",
        deploymentName: "Create Instance",
        status: "ENDED",
      },
    ],
    envEntityId: 322,
    description: "desc",
    appWFUri:
      "Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Provision_Apps_EKS_Cluster",
    envWFUri:
      "Process/cloudclapp-wf/Provision_an_EKS_Cluster__AWS_/Provision_an_EKS_Cluster__AWS_",
    envUbiqubeId: "00pA143",
  },
  {
    envName: "hto env 01",
    envId: 144,
    envReference: "0419674e-a030-4fb9-b47a-94bcb8de6d0e",
    status: "OK",
    cclapOwner: 125,
    deployments: [
      {
        deploymentId: "126094",
        deploymentName: "Create Instance",
        status: "ENDED",
      },
      {
        deploymentId: "126093",
        deploymentName: "Create Instance",
        status: "ENDED",
      },
      {
        deploymentId: "126092",
        deploymentName: "Create Instance",
        status: "ENDED",
      },
      {
        deploymentId: "126091",
        deploymentName: "Create Instance",
        status: "ENDED",
      },
      {
        deploymentId: "126088",
        deploymentName: "Create Instance",
        status: "ENDED",
      },
    ],
    envEntityId: 323,
    description: "2nd",
    appWFUri:
      "Process/cloudclapp-wf/Provision_Apps_EKS_Cluster/Provision_Apps_EKS_Cluster",
    envWFUri:
      "Process/cloudclapp-wf/Provision_an_EKS_Cluster__AWS_/Provision_an_EKS_Cluster__AWS_",
    envUbiqubeId: "00pA144",
  },
];
