export const cloudeVendorRegions = {
  aws: [
    "US East (Ohio) - us-east-2",
    "US East (N. Virginia) - us-east-1",
    "US West (N. California) - us-west-1",
    "US West (Oregon) - us-west-2",
    "Africa (Cape Town) - af-south-1",
    "Asia Pacific (Hong Kong) - ap-east-1",
    "Asia Pacific (Jakarta) - ap-southeast-3",
    "Asia Pacific (Mumbai) - ap-south-1",
    "Asia Pacific (Osaka) - ap-northeast-3",
    "Asia Pacific (Seoul) - ap-northeast-2",
    "Asia Pacific (Singapore) - ap-southeast-1",
    "Asia Pacific (Sydney) - ap-southeast-2",
    "Asia Pacific (Tokyo) - ap-northeast-1",
    "Canada (Central) - ca-central-1",
    "Europe (Frankfurt) - eu-central-1",
    "Europe (Ireland) - eu-west-1",
    "Europe (London) - eu-west-2",
    "Europe (Milan) - eu-south-1",
    "Europe (Paris) - eu-west-3",
    "Europe (Stockholm) - eu-north-1",
    "Middle East (Bahrain) - me-south-1",
    "South America (São Paulo) - sa-east-1",
  ],
  gcp: [
    "Changhua County, Taiwan - asia-east1",
    "Hong Kong - asia-east2",
    "Tokyo, Japan - asia-northeast1",
    "Osaka, Japan - asia-northeast2",
    "Seoul, South Korea - asia-northeast3",
    "Mumbai, India - asia-south1",
    "Delhi, India - asia-south2",
    "Jurong West, Singapore - asia-southeast1",
    "Jakarta, Indonesia - asia-southeast2",
    "Sydney, Australia - australia-southeast1",
    "Melbourne, Australia - australia-southeast2",
    "Warsaw, Poland - europe-central2",
    "Hamina, Finland - europe-north2",
    "Madrid, Spain - europe-southwest1",
    "St. Ghislain, Belgium - europe-west1",
    "London, England - europe-west2",
    "Frankfurt, Germany - europe-west3",
    "Eemshaven, Netherlands - europe-west4",
    "Zurich, Switzerland - europe-west6",
    "Milan, Italy - europe-west8",
    "Paris, France - europe-west9",
    "Tel Aviv, Israel - me-west1",
    "Montréal, Québec - northamerica-northeast1",
    "Toronto, Ontario - northamerica-northeast2",
    "São Paulo, Brazil - southamerica-east1",
    "Santiago, Chile - southamerica-west1",
    "Council Bluffs, Iowa - us-central1",
    "Moncks Corner, South Carolina - us-east1",
    "Ashburn, Virginia - us-east4",
    "Columbus, Ohio - us-east5",
    "Dallas, Texas - us-south1",
    "The Dalles, Oregon - us-west1",
    "Los Angeles, California - us-west2",
    "Salt Lake City, Utah - us-west3",
    "Las Vegas, Nevada - us-west4",
  ],
  azure: [
    "South Africa North",
    "South Africa West",
    "Australia Central",
    "Australia Central 2",
    "Australia East",
    "Australia Southeast",
    "Central India",
    "East Asia",
    "Japan East",
    "Japan West",
    "Jio India Central",
    "Jio India West",
    "Korea Central",
    "Korea South",
    "Southeast Asia",
    "South India",
    "West India",
    "Canada Central",
    "Canada East",
    "China East",
    "China East 2",
    "China East 3",
    "China North",
    "China North 2",
    "China North 3",
    "France Central",
    "France South",
    "Germany North",
    "Germany West Central",
    "North Europe",
    "Norway East",
    "Norway West",
    "Sweden Central",
    "Switzerland North",
    "Switzerland West",
    "UK South",
    "UK West",
    "West Europe",
    "UAE Central",
    "UAE North",
    "Brazil South",
    "Brazil Southeast",
    "Central US",
    "East US",
    "East US 2",
    "North Central US",
    "South Central US",
    "West Central US",
    "West US",
    "West US 2",
    "West US 3",
  ],
};
