export const tenantList = [
  {
    value: "ARA",
    id: 15,
    ubiqubeId: null,
    label: "Amit",
  },
  {
    value: "bfR",
    id: 28,
    ubiqubeId: null,
    label: "bfR",
  },
  {
    value: "fbo",
    id: 11,
    ubiqubeId: null,
    label: "fbo_tenant",
  },
  {
    value: "FUJ",
    id: 12,
    ubiqubeId: null,
    label: "Fujitsu",
  },
  {
    value: "hto",
    id: 69,
    ubiqubeId: null,
    label: "Htoper",
  },
  {
    value: "PRN",
    id: 2,
    ubiqubeId: null,
    label: "PRNOperator",
  },
  {
    value: "MSA",
    id: 10,
    ubiqubeId: null,
    label: "UBIqube",
  },
];

export const userDetails = {
  id: 1,
  baseRole: { id: 1, name: "Super Administrateur" },
  externalReference: "NCLG1",
  login: "ncroot",
  operator: {
    id: 1,
    contacts: [],
    abonnes: [],
    baseUrl: null,
    isPartner: false,
    name: "UBIqube",
    prefix: "NCL",
    address: {
      city: "",
      country: "",
      fax: "",
      mail: "",
      phone: "",
      streetName1: "",
      streetName2: "",
      streetName3: "",
      zipCode: "",
    },
    sort: "NAME",
    companyType: "",
  },
  pwd: "",
  userType: 2,
  acteurId: 1,
  address: {
    city: "Dublin",
    country: "Ireland",
    fax: "111111",
    mail: "support@ubiqube.com",
    phone: "10000000000",
    streetName1: "Some street address1",
    streetName2: "Some street address2",
    streetName3: "Some street address3",
    zipCode: "000000",
  },
  delegationProfileId: 0,
  delegations: null,
  delegationsPerSubtenant: {},
  netceloId: {
    ubiID: "NCLG1",
    thePrefix: "NCL",
    id: 1,
    customerPrefix: "NCL",
  },
  firstname: "Clark",
  manageAllUsers: true,
  name: "ncroot",
  sort: "NAME",
  ldapAuthentication: false,
  delegationProfilePerCustomer: {},
};

export const loginSuccess = {
  message: "authenticated",
  userDetails,
  token:
    "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuY3Jvb3QiLCJpYXQiOjE1NjIxNjEwNDQsImx2bCI6IjEiLCJleHAiOjE1NjIyNDc0NDR9.fDYfGQqJpWgI0iGtwuUWTFXSa2T51JlSWXYPkrx2QgwBy3vPfKeD6xc0RrH2ekZdh2rAucCUclunNl1tXBCwxw",
};
